<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TagSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
       $interestsArray = [
    'Voetbal',
    'Handbal',
    'Volleybal',
    'Gymnastiek, turnen',
    'Hardlopen, atletiek',
    'Zwemmen, waterpolo',
    'Tennis',
    'Badminton',
    'Hengelsport',
    'Hockey',
    'Roeien',
    'Zeilen',
    'Watersport',
    'Golf',
    'Judo',
    'Boksen',
    'Wandelsport',
    '(kruis-)boogschieten',
    'Biljarten, darten',
    'Tafeltennis',
    'Dammen, schaken',
    'Bridgen, kaarten',
    'Sjoelbakken',
    'Honkbal, softbal',
    'Basketbal',
    'Korfbal',
    'Kegelen, bowling',
    'Rugby',
    'Paardrijden',
    'Motorrijden',
    '(kunst-)schaatsen',
    'Ijshockey',
    'Skeeleren, skaten',
    'Jeu de boules, petanque',
    'Joggen, steppen',
    'Fitness, tae-bo',
    'Mediteren',
    'Bio-energetica',
    'Muziek & Dans in het algemeen',
    'Lichte muziek',
    'Pop, rock, r&b, rap',
    'Opera, operette',
    'Kerkmuziek',
    'Zingen individueel',
    'Koorzang',
    'Fanfare',
    'Piano',
    'Orgel, synthesizer',
    'Xylofoon',
    'Viool',
    'Cello',
    'Bas',
    'Gitaar',
    'Trompet, trombone',
    'Saxofoon',
    '(blok)fluit',
    'Dwarsfluit',
    'Mondharmonica',
    'Accordeon',
    'Percussie',
    'Didgeridoo',
    'Djembee',
    'Dans hobbies',
    'Klassiek ballet',
    'Jazz-ballet',
    'Volksdansen',
    'Stijldansen',
    'Street-dance',
    'Break-dance',
    'Lezen',
    'Radio luisteren',
    'Televisie kijken',
    'Film opnemen',
    'Youtube filmpjes maken',
    'Computer: spelletjes',
    'Internet: surfen',
    'Chatten, e-mailen',
    'Foto-scans bewerken',
    'Software ontwikkelen',
    'Cultuur en kunst hobbies',
    'Beeldende kunst',
    'Geografie',
    'Sterrenkunde',
    'Godsdienst(en)',
    'Volkenkunde',
    'Vreemde talen',
    'Filosofie, religie',
    'Zelfontplooiing',
    'Architectuur',
    'Toneel, theater',
    'Cabaret',
    'Biotechnologie',
    'Lucht-/ruimtevaart',
    'Film & fotografie',
    'Stamboomonderzoek',
    'schrijven',
    'Vrijwilligerswerk',
    'Wandelen',
    'Fietsen',
    'Tuinieren',
    'Bloemen kweken',
    'Planten verzorgen',
    'Vogels observeren',
    'Honden fokken',
    'Paard(en) verzorgen',
    'Aquarium',
    'Tekenen',
    'Schilderen',
    'Beeldhouwen',
    'Boetseren',
    'Houtbewerken',
    'Modelbouw',
    'Handwerken',
    'Knutselen, frutselen',
    'Klussen in huis',
    'Discotheek',
    'Naar vrienden',
    'Restaurant uit eten',
    'Theater',
    'Kroeg',
    'Koken',
    'Bakken',
    'Wijnproeven',
    'Bierbrouwen',
    'Koffie zetten',
    'Thee proeven',
    'Haken',
    'Breien',
    'Quilten',
    'Podcast maken',
    'Vloggen',
    'Reizen',
    'Backpacken',
    'Camping',
    'Wandelen in de natuur',
    'Kamperen',
    'Reisfotografie',
    'Reisbloggen',
    'Astronomie',
    'Amateurastronomie',
    'Sterren kijken',
    'Ruimteverkenning',
    'Mindfulness',
    'Spirituality',
    'Astrology',
    'Numerology',
    'Kalligrafie',
    'Aquarelschilderen',
    'Olieverfschilderen',
    'Grafisch ontwerp',
    '3D-printen',
    'Modeltreinen',
    'Sculptuur',
    'Edelsmeden',
    'Zelfverdediging',
    'Krav Maga',
    'Schermen',
    'Worstelen',
    'Boulderen',
    'Paddleboarding',
    'Kitesurfen',
    'Kajakken',
    'Rotsklimmen',
    'Paintball',
    'Lasergamen',
    'Escape rooms',
    'Bungeejumpen',
    'Paragliden',
    'Motorracen',
    'Skiën',
    'Snowboarden',
    'IJsklimmen',
    'Kiteboarden',
    'Wakeboarden',
    'Karten',
    'Zorbing',
    'Skydiven',
    'Parachutespringen',
    'Ballroomdansen',
    'Argentijnse tango',
    'Salsa dansen',
    'Hiphop dansen',
    'Flamenco dansen',
    'Magie',
    'Goochelen',
    'Kaarttrucs',
    'Mentaleisme',
    'Vuurjongleren',
    'Luchtacrobatiek',
    'Graffiti',
    'Graffitikunst',
    'Street art',
    'Keramiek',
    'Pottenbakken',
    'Bonsai kweken',
    'Stempelkunst',
    'Miniatuurmodellen',
    'Antiek verzamelen',
    'Postzegelverzamelen',
    'Munten verzamelen',
    'Stripboeken verzamelen',
    'Actiefiguur verzamelen',
    'Vinylplaten verzamelen',
    'Sneaker verzamelen',
    'Parfum verzamelen',
    'Sieraden verzamelen',
    'Edelstenen verzamelen',
    'Planten verzamelen',
    'Vogelspotten',
    'Insecten verzamelen',
    'Amateurmeteorologie',
    'Natuurfotografie',
    'Vogelfotografie',
    'Onderwaterfotografie',
    'Sportfotografie',
    'Macrofotografie',
    'Dronefotografie'
];

        foreach ($interestsArray as $tag) {
            DB::table('tags')->insert([
                'name' => $tag,
                // random rgb color
                'color' => rand(0, 255) . ',' . rand(0, 255) . ',' . rand(0, 255)
            ]);
        }
    }
}
